/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pointgrey_api_PointGreyCameraInterface */

#ifndef _Included_com_pointgrey_api_PointGreyCameraInterface
#define _Included_com_pointgrey_api_PointGreyCameraInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    createContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_createContext
  (JNIEnv *, jclass);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    destroyContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_destroyContext
  (JNIEnv *, jclass);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    getNumOfCameras
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_getNumOfCameras
  (JNIEnv *, jclass);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    connectToDefaultCamera
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_connectToDefaultCamera
  (JNIEnv *, jclass);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    startCapture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_startCapture
  (JNIEnv *, jclass);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    stopCapture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_stopCapture
  (JNIEnv *, jclass);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    getImage
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_getImage
  (JNIEnv *, jclass);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    storeImage
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_storeImage
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    getCameraName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_getCameraName
  (JNIEnv *, jclass);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    getSupportedModes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_getSupportedModes
  (JNIEnv *, jclass);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    setCameraMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_setCameraMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    getPropertyInfo
 * Signature: (I)Lcom/pointgrey/api/PGPropertyInfo;
 */
JNIEXPORT jobject JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_getPropertyInfo
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    getProperty
 * Signature: (I)Lcom/pointgrey/api/PGProperty;
 */
JNIEXPORT jobject JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_getProperty
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_pointgrey_api_PointGreyCameraInterface
 * Method:    setProperty
 * Signature: (ILcom/pointgrey/api/PGProperty;)V
 */
JNIEXPORT void JNICALL Java_com_pointgrey_api_PointGreyCameraInterface_setProperty
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
